export const HOME_PAGE_NEXT = "HOME_PAGE_NEXT";
export const HOME_PAGE_PREV = "HOME_PAGE_PREV";
export const HOME_PAGE_CLEAR = "HOME_PAGE_CLEAR";
export const TOKEN_UPDATE = "TOKEN_UPDATE";
export const TOKEN_CLEAR = "TOKEN_CLEAR";