export const HOME_PAGE_NEXT = "HOME_PAGE_NEXT";
export const HOME_PAGE_PREV = "HOME_PAGE_PREV";
export const HOME_PAGE_CLEAR = "HOME_PAGE_CLEAR";
export const COMMENT_ACCOUNT_SAVE = "COMMENT_ACCOUNT_SAVE";
export const COMMENT_ACCOUNT_CLEAR = "COMMENT_ACCOUNT_CLEAR";
export const COMMENT_TOGGLE_SAVE = "COMMENT_TOGGLE_SAVE";
export const COMMENT_TOGGLE_CLEAR = "COMMENT_TOGGLE_CLEAR";